### ISSUE TITLE
java.lang.IllegalStateException in PhotoData.copyFromSerialized

### ISSUE THREAD

**Issue by SteMaker** [SteMaker/AndroidArbeitsbericht#14]
Caused by java.lang.IllegalStateException: bitmap must not be null
       at com.stemaker.arbeitsbericht.data.PhotoData.copyFromSerialized(PhotoData.kt:54)
       at com.stemaker.arbeitsbericht.data.PhotoContainerData.copyFromSerialized(PhotoData.kt:18)
       at com.stemaker.arbeitsbericht.data.ReportData.copyFromSerialized(ReportData.kt:74)
       at com.stemaker.arbeitsbericht.data.ReportData.access$copyFromSerialized(ReportData.kt:13)
       at com.stemaker.arbeitsbericht.data.ReportData$Companion.getReportFromJson(ReportData.kt:91)
       at com.stemaker.arbeitsbericht.StorageHandler.readReportFromFile(StorageHandler.kt:164)
       at com.stemaker.arbeitsbericht.StorageHandler.selectReportById(StorageHandler.kt:119)
       at com.stemaker.arbeitsbericht.StorageHandler.selectReportById$default(StorageHandler.kt:116)
       at com.stemaker.arbeitsbericht.StorageHandler.initialize(StorageHandler.kt:62)
       at com.stemaker.arbeitsbericht.StorageHandlerKt.storageHandler(StorageHandler.kt:16)
       at com.stemaker.arbeitsbericht.MainActivity.onCreate(MainActivity.kt:42)
       at android.app.Activity.performCreate(Activity.java:7957)
       at android.app.Activity.performCreate(Activity.java:7946)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8107)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by SteMaker** [comment]
Fixed with 2.5.0
